services:
  mindillu_vite:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_PATH: ${VITE_BASE_PATH:-/mindillustrate/frontend/}
    container_name: mindillu-scenecreator
    ports:
      - "3004:80"

volumes:
  postgres_data:
