services:
  mindillustrate-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_PATH: /mindillustrate/frontend/
        VITE_GOOGLE_TTS_KEY: ${VITE_GOOGLE_TTS_KEY:-}
    container_name: mindillustrate-frontend
    ports:
      - "3004:3004"
    restart: unless-stopped
